# Generated by Django 4.2.16 on 2024-12-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0012_remove_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, choices=[('programming', 'Programming'), ('education', 'Education'), ('crm', 'CRM')], max_length=20, null=True),
        ),
    ]
