# Generated by Django 4.2.16 on 2024-12-09 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0014_alter_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.project'),
        ),
    ]
